version: '3'
services:
  tpu_container:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    image: eu.gcr.io/${PROJECT_ID}/tae-tpu:v1
    container_name: tae-tpu-container
    privileged: true
    environment:
      # PyTorch/XLA TPU configuration
      - PJRT_DEVICE=TPU
      # Project variables
      - PROJECT_ID=${PROJECT_ID}
    volumes:
      # System volumes - essential for TPU access
      - /dev:/dev
      - /lib/libtpu.so:/lib/libtpu.so
      # Authentication - create keys directory at runtime
      - ${PWD}/config/${SERVICE_ACCOUNT_JSON}:/app/service-account.json:ro
      # Application volume - only mount the src directory
      - ${PWD}/src:/app/mount/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.isdir('/app/mount/src') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s