version: '3'
services:
  tpu_container:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    image: eu.gcr.io/${PROJECT_ID}/tae-tpu:v1
    container_name: tae-tpu-container
    privileged: true
    environment:
      # PyTorch/XLA TPU configuration
      - PJRT_DEVICE=TPU
      # Project variables
      - PROJECT_ID=${PROJECT_ID}
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      # System volumes - essential for TPU access
      - /dev:/dev
      - /lib/libtpu.so:/lib/libtpu.so
      # Authentication
      - ${PWD}/config/${SERVICE_ACCOUNT_JSON}:/app/keys/service-account.json:ro
      # Application volume - single mount point with organized subdirectories
      - ${PWD}/mount:/app/mount
    ports:
      - "5000:5000"
      - "6006:6006"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.isdir('/app/mount') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s