version: '3'
services:
  tpu-container:
    image: ${IMAGE_NAME}:latest
    container_name: ${CONTAINER_NAME}
    privileged: true
    network_mode: host
    environment:
      - PJRT_DEVICE=TPU
      - TF_CPP_MIN_LOG_LEVEL=0
      - XLA_FLAGS=--xla_dump_to=/app/mount/xla_dumps
    volumes:
      - ./src:/app/mount
      - /usr/share/tpu/:/usr/share/tpu/
      - /lib/libtpu.so:/lib/libtpu.so
    restart: unless-stopped