version: '3.8'

services:
  tpu-service:
    build:
      context: ../../..  # Points to project root
      dockerfile: src/setup/docker/Dockerfile
    image: eu.gcr.io/${PROJECT_ID}/tae-tpu:v1
    container_name: tae-tpu-container
    privileged: true
    environment:
      # PyTorch/XLA TPU configuration
      - PJRT_DEVICE=TPU
      # Project variables
      - PROJECT_ID=${PROJECT_ID}
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      # System volumes - essential for TPU access
      - /dev:/dev
      - /lib/libtpu.so:/lib/libtpu.so
      # Authentication
      - ../../source/${SERVICE_ACCOUNT_JSON}:/app/keys/service-account.json:ro
      # Application volumes
      - ../../../mount:/app/mount
      - ../../../data:/app/data
      - ../../../models:/app/models
      - ../../../logs:/app/logs
    ports:
      - "5000:5000"
      - "6006:6006"
    restart: unless-stopped